## HW2-2
### 20180711


#### 網路爬蟲
```{r}
source('pttTestFunction.R')
id = c(1062:1071)
URL = paste0("https://www.ptt.cc/bbs/Finance/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)
```

#### 文本清理
```{r}
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))

# 移除可能有問題的符號

toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "時間")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")


docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "文章")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "網址")
docs <- tm_map(docs, toSpace, "轉錄")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "啦")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "喔")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "標題")
docs <- tm_map(docs, toSpace, "請益")
docs <- tm_map(docs, toSpace, "請問")



#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space) 

docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs
```

#### 詞頻矩陣
```{r}

mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```

#### 文字雲
```{r}

wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=50,max.words=150,
          random.order=TRUE, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```

