---
title: "report"
author: "yshuhan"
date: "2018年7月18日"
output: html_document
---
data from https://www.kaggle.com/c/kobe-bryant-shot-selection/data

```{r}
library(dplyr)
library(ggplot2)
```


```{r}
# 讀入資料

data <- read.csv("data.csv", stringsAsFactors = FALSE)
```

```{r}
train <- data[!is.na(data$shot_made_flag),]
test <- data[is.na(data$shot_made_flag),]


train$shot_made_flag <- as.factor(train$shot_made_flag)
```



```{r}
# 查看欄位名稱

names(train)
```



```{r}
# 將vector轉為factor

train$shot_made_flag <- factor(train$shot_made_flag, levels = c("1", "0"))
```

```{r}
pplot <- function(feat) {
    feat <- substitute(feat)
    ggplot(data = train, aes_q(x = feat)) +
        geom_bar(aes(fill = shot_made_flag), stat = "count", position = "fill") +
    scale_fill_brewer(palette = "Set1", direction = -1) +
     ggtitle(paste("accuracy by", feat))

}

# alpha值是透明度，介於0到1

courtplot <- function(feat) {
        feat <- substitute(feat)
    train %>% 
    ggplot(aes(x = lon, y = lat)) +
        geom_point(aes_q(color = feat), alpha = 0.7, size = 3) +
        ylim(c(33.7, 34.0883)) +
        scale_color_brewer(palette = "Set1") +
        theme_void() +
        ggtitle(paste(feat))
}
```

### 不同投籃方式在球場上的分布

```{r}
courtplot(combined_shot_type)
```

### 上圖難以辨識故將其中一項作淡化處理

```{r}
# 使用filter查找出特定條件為true的情況，這裡把"Jump Shot"找出來設為較不顯眼的顏色，重新畫圖
  
# ylim是在y軸設定界限，讓他只呈現出範圍內的資料
ggplot() +
    geom_point(data = filter(train, combined_shot_type == "Jump Shot"),
               aes(x = lon, y = lat), color = "grey", alpha = 0.3, size = 2) +
    geom_point(data = filter(train, combined_shot_type != "Jump Shot"),
                   aes(x = lon, y = lat, 
                       color = combined_shot_type), alpha = 0.7, size = 3) +
    ylim(c(33.7, 34.0883)) +
    scale_color_brewer(palette = "Set1") +
    theme_void() +
    ggtitle("Shot Types")
```

### 放大檢視排除特定項目後，與籃框相距小於等於5時的投籃命中情形。1代表進，0代表沒進。

```{r}
ggplot() +
        geom_point(data = filter(train, combined_shot_type != "Jump Shot",
                                 shot_distance < 5),
                       aes(x = loc_x, y = loc_y, 
                           color = shot_made_flag),
                   alpha = 0.7, size = 3) +
        scale_color_brewer(palette = "Set1") +
        geom_point(aes(x =0, y = 0), size = 5, shape = 4) +
    theme_void() +
    ggtitle("Shots from up close")
```



```{r}
# facet_grid():根據shot_made_flag分成兩個圖

ggplot(train, aes(x = loc_x, y = loc_y)) +
    geom_point(aes(color = shot_made_flag), alpha = 0.5, size = 0.5) +
    ylim(c(-50, 400)) +
    theme_void() +
    scale_color_brewer(palette = "Set1") +
    facet_grid(~ shot_made_flag) +
    labs(title = "Shots Made(Blue) vs. Shots Missed(Red)")
```

### 進球數在X軸上的分布情形

```{r}


x_bins <- cut(train$loc_x, breaks = 25)
pplot(x_bins) + geom_bar() + ggtitle("Shot Distribution by x_bins") +
    theme(axis.text.x = element_blank())
```

```{r}
pplot(x_bins) + theme(axis.text.x = element_blank())
```


```{r}
# desc()按遞減方式排序變數

train %>% count(action_type) %>%
    arrange(desc(n)) %>% filter(n < 20) -> actions
train$action_type[train$action_type %in% actions$action_type] <- "Other"
```
```{r}


prop.table(table(train$action_type, train$shot_made_flag),1) -> temp
as.data.frame.matrix(temp) -> temp
temp$shot <- rownames(temp)
ggplot(temp, aes(x = reorder(shot, `1`), y = 1)) +
geom_point(aes(y = `1`), size = 3, color = " dark blue", stat = "identity") +
    coord_flip() +
    labs(y = "Accuracy", x = "", title = "Accuracy by Shot_type")
```

